language: java
jdk:
  - oraclejdk8

#script: mvn clean javadoc:jar source:jar package install deploy --settings travis-settings.xml

before_script:
  - openssl aes-256-cbc -K $encrypted_672a837fba30_key -iv $encrypted_672a837fba30_iv -in .travisgocddeploykey.enc -out .travisgocddeploykey -d
  - chmod go-rwx .travisgocddeploykey
  - eval `ssh-agent -s`
  - ssh-add .travisgocddeploykey
  - git config user.name "Travis-CI"
  - git config user.email "noreply@travis-ci.org"
  - echo ".travisgocddeploykey" >> .git/info/exclude
  - echo "pom.xml.releaseBackup" >> .git/info/exclude
  - echo "release.properties" >> .git/info/exclude
  - echo "target/" >> .git/info/exclude
  - git fetch -p
  - git checkout master
  - git pull

script:
  - chmod 777 deploy.sh
  - ./deploy.sh

branches:
  only:
    - master

